services:
  sunshine-monitor-clickhouse:
    image: clickhouse:25.10
    container_name: sunshine-monitor-clickhouse
    restart: always
    ports:
      - '8124:8123'
      - '9001:9000'
    environment:
      CLICKHOUSE_USER: sunshine
      CLICKHOUSE_PASSWORD: 123456
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_init:/docker-entrypoint-initdb.d
  sunshine-monitor-postgres:
    image: postgres:18.1
    container_name: sunshine-monitor-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: sunshine
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql_data:/var/lib/postgresql
networks:
  default:
    name: sunshine-monitor-network
    driver: bridge
